# Generated by Django 4.0.5 on 2022-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_articul_alter_product_brend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.SlugField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
